--pyuic5 ui\MainWindow.ui -o widgets_descriptions\MainWindow.py
--pyside2-uic ui\MainWindow.ui -o widgets_descriptions\MainWindow.py
--.open "C:/Users/makar.zotov/Documents/VKRdraft/db.sqlite"

DB = C:\Study\VKR\project\vitazub_desktop\db.sqlite

SERVER = http://127.0.0.1:8000/

CREATE TABLE DOCTOR (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME VARCHAR(50));

INSERT INTO DOCTOR (NAME)
VALUES ('Иванов');

INSERT INTO DOCTOR (NAME)
VALUES ('Петров');

CREATE TABLE CLIENT (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    S_NAME VARCHAR(50),
    F_NAME VARCHAR(50),
    L_NAME VARCHAR(50));

CREATE TABLE RECORDING (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    DOCTOR_ID INTEGER,
    CLIENT_ID INTEGER,
    START_DTTM DATETIME,
    END_DTTM DATETIME
    );

INSERT INTO RECORDING (DOCTOR_ID, CLIENT_ID, START_DTTM, END_DTTM)
VALUES (1, 2, '2021-07-15 10:00:00', '2021-07-15 11:00:00');

INSERT INTO RECORDING (DOCTOR_ID, CLIENT_ID, START_DTTM, END_DTTM)
VALUES (1, 1, '2021-07-15 12:00:00', '2021-07-15 13:00:00');

SELECT L_RECORDING_ID, H_CLIENT_ID, START_TM, END_TM, FIO, PHONE, ADDITIONAL_PHONE, COMMENT
FROM
(SELECT NULL L_RECORDING_ID, NULL H_CLIENT_ID,
    '08:00' START_TM,
    STRFTIME('%H:%M', MIN(START_DTTM)) END_TM,
    'Свободно' FIO, NULL PHONE, NULL ADDITIONAL_PHONE, NULL COMMENT
FROM V_RECORDING
WHERE H_DOCTOR_ID = 18
    AND STRFTIME('%Y-%m-%d', START_DTTM) = '2022-02-14'
UNION ALL
SELECT L_RECORDING_ID, H_CLIENT_ID,
    STRFTIME('%H:%M', START_DTTM) START_TM,
    STRFTIME('%H:%M', END_DTTM) END_TM,
    FIO, PHONE, ADDITIONAL_PHONE, COMMENT
FROM V_RECORDING
WHERE H_DOCTOR_ID = 18
    AND STRFTIME('%Y-%m-%d', START_DTTM) = '2022-02-14'
UNION ALL
SELECT NULL L_RECORDING_ID, NULL H_CLIENT_ID,
    STRFTIME('%H:%M', END_DTTM) START_TM,
    COALESCE(STRFTIME('%H:%M', LEAD(START_DTTM) OVER (ORDER BY START_DTTM)), '18:00') END_TM,
    'Свободно' FIO, NULL PHONE, NULL ADDITIONAL_PHONE, NULL COMMENT
FROM V_RECORDING
WHERE H_DOCTOR_ID = 18
    AND STRFTIME('%Y-%m-%d', START_DTTM) = '2022-02-14') SH
WHERE NOT (FIO == 'Свободно' AND START_TM == END_TM)
ORDER BY START_TM;
